export const IS_AUTHENTICATED = 'IS_AUTHENTICATED';
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';
export const SEND_APPLICATION = 'SEND_APPLICATION';
export const LIKE_UNLIKE_PRODUCT = 'LIKE_UNLIKE_PRODUCT';

